# Generated by Django 4.2.3 on 2023-09-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=250, unique=True)),
                ('cimage', models.ImageField(blank=True, upload_to='category')),
                ('cdesc', models.TextField(blank=True)),
                ('cslug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('cname',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250, unique=True)),
                ('pslug', models.SlugField(unique=True)),
                ('pdesc', models.TextField(blank=True)),
                ('pimage', models.ImageField(blank=True, upload_to='products')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pcreate', models.DateTimeField(auto_now_add=True)),
                ('pstock', models.IntegerField()),
                ('pavailable', models.BooleanField(default=True)),
                ('pupdate', models.DateTimeField(auto_now=True)),
                ('pcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('pname',),
            },
        ),
    ]
