# Generated by Django 4.2.5 on 2023-09-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pslug',
            new_name='slug',
        ),
    ]
