# Generated by Django 4.2.5 on 2023-09-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_rename_cslug_category_slug_rename_pslug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pcategory',
            new_name='category',
        ),
    ]
